#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
IMAGE=fidoip32:1.0.5_5-1_1

docker run -v $DIR/home/fido:/home/fido -v $DIR/usr/local/etc:/usr/local/etc -v $DIR/usr/local/bin:/usr/local/bin --rm -it $IMAGE $*
